---
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
firstname <- "Orange"
middlename <- "Marshall"
lastname <- "Blackstar"
nickname <- "something"
phone <- "999 222 0000"
```
---
title: "`r firstname` `r middlename` `r lastname`"
output: pdf_document
fontfamily: arev
geometry: margin=1cm
header-includes:
 - \usepackage{fontawesome}
---
\pagenumbering{gobble}
\begin{center}
\faEnvelope{\space} \href{mailto:`r nickname`@gmail.com}{`r nickname`@gmail.com} |
\faPhone{\space} `r phone` | 
\faGithub{\space} \href{https://github.com/`r nickname`}{`r nickname`} | 
\faLinkedin{\space} \href{https://www.linkedin.com/in/`r firstname`-`r middlename`-`r lastname`}{www.linkedin.com/in/`r firstname`-`r middlename`-`r lastname`}
\end{center}

## Education

**Certificate Program in Database and Data Analytics**

UC Santa Cruz Silicon Valley Extension, Santa Clara, CA, 2017 – 2018

* Coursework:
    + Big Data (Apache Hadoop and Spark)
    + Machine Learning Algorithms
    + Predictive Analytics

**Bachelor of Science in Electrical Engineering**

Monterrey Institute of Technology and Higher Education, Guadalajara, Mexico, 1999–2003

  * Graduated with Honors.

## Skills

*Programming* | *Scripting* | *Big Data*          | *Analytics/Database* | *Hardware* | *Others*
--------------|-------------|---------------------|----------------------|------------|----------------
C / C++       | Python      | Spark/Hadoop        | R                    | PCIe       | GNU Toolchain
Java / Scala  | Perl        | Hive                | SQL                  | Verilog    | AWS (EC2, EMR)

## Professional Experience

**Principal Software Engineer, Cadence (Sept 2015 – Current)**

Current project is a PCIe Protocol Model written in C. Code has a lot of legacy from many years and it is around 400,000 lines. It targets Linux systems.

  * Architected and developed many features of the code.
  * Tracked, debugged and fixed several customer issues using the JIRA system.
  * Trained junior engineers and conducted code reviews as needed.
  * Developed a Code Analytics engine that scrapes the repository (17 years of history) and identifies hotspots of the code based on the number of edits. A decision tree model is built. Written in Python and R.

**Component Design Engineer, Intel Corporation (Feb 2009 – Sept 2015)**

Worked on design and verification of a PCIe/USB/SATA PHY, a Server Processor and a GPU.

Coded a pre-silicon test environment in a mixture of C/C++, System Verilog and Perl scripts.

  * Developed a library of base classes which were the foundation for a random test environment.
  * Coded wrappers to interface C++ code to a digital logic simulator.
  * Coded Perl scripts to automate the simulation/checking process.
  
## Projects

**Wind Analysis Of Northern Yucatan Coast for Kiteboarding (Dec 2018)**

Spark SQL project written in a Jupyter notebook. It uses a very innovative method to convert an irregular time series into an equally spaced time series. Covers almost 10 years of data. Can run on Databricks.

https://github.com/`r nickname`/windMining/blob/master/kbWindNorYuc/kbWindNorYuc.ipynb
